### ISSUE TITLE
Upgranding to Symfony 3.4

### ISSUE THREAD

**Issue by pdias** [nelmio/NelmioJsLoggerBundle#19]
After upgrade symfony to 3.4 i have this warning.

> Using Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition::cannotBeEmpty() at path "nelmio_js_logger.allowed_levels" has no effect, consider requiresAtLeastOneElement() instead. In 4.0 both methods will behave the same.

Thanks.

Paulo Dias

**Comment by stephanvierkant** [comment]
Fixed by #20
