### ISSUE TITLE
Symfony 4.2 Deprecation notices - use AbstractController instead

### ISSUE THREAD

**Issue by benr77** [nelmio/NelmioJsLoggerBundle#30]
Symfony 4.2 is showing deprecation warnings:

`The "Nelmio\JsLoggerBundle\Controller\LogController" class extends "Symfony\Bundle\FrameworkBundle\Controller\Controller" that is deprecated since Symfony 4.2, use {@see AbstractController} instead.`

Can we change `LogController` to extend `AbstractController` instead? As far as I can tell we'd only need to use constructor injection for the JS logger service instead of using `$this->get()` etc

Any thoughts? Happy to put together a PR if needed.

**Comment by Seldaek** [comment]
A PR would be great for this if you have time
